name: Flat

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Or any other version of Node.js
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Fetch data
        uses: githubocto/flat@v3
        with:
          http_url: https://www.canada.ca/content/dam/ircc/documents/json/ee_rounds_123_en.json
          downloaded_filename: data/ee_rounds_123_en.json # Saves the file in src/data folder
      - name: Install Node.js dependencies
        run: npm install fs path
      - name: Split JSON into batches
        run: node splitJsonIntoBatches.js
    